apiVersion: v1
kind: Service
metadata:
 name: spring-boot
spec:
 type: NodePort
 selector:
   app: spring-boot
 ports:
 - name: test
   protocol: TCP
   port: 8080
   targetPort: 8080
   nodePort: 31110
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: spring-boot 
spec: 
 replicas: 1
 strategy: 
  type: RollingUpdate 
 selector: 
  matchLabels: 
   app: spring-boot 
 template: 
   metadata: 
    labels: 
     app: spring-boot
   spec: 
    containers: 
    - name: spring-boot 
      image: khalil15832/spring-boot:latest
      ports:
      - containerPort: 8080
